#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libgovirt
Version  : 0.3.7
Release  : 4
URL      : https://gitlab.gnome.org/GNOME/libgovirt/-/archive/v0.3.7/libgovirt-v0.3.7.tar.gz
Source0  : https://gitlab.gnome.org/GNOME/libgovirt/-/archive/v0.3.7/libgovirt-v0.3.7.tar.gz
Summary  : goVirt is a GLib binding for oVirt REST API
Group    : Development/Tools
License  : LGPL-2.1
Requires: libgovirt-data = %{version}-%{release}
Requires: libgovirt-lib = %{version}-%{release}
Requires: libgovirt-license = %{version}-%{release}
Requires: libgovirt-locales = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : gettext
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(rest-0.7)

%description
GoVirt is a GObject wrapper for the oVirt REST API [1]. It will
only provide very basic functionality as the goal is to
autogenerate a full wrapper as it is already done for the python
bindings.

%package data
Summary: data components for the libgovirt package.
Group: Data

%description data
data components for the libgovirt package.


%package dev
Summary: dev components for the libgovirt package.
Group: Development
Requires: libgovirt-lib = %{version}-%{release}
Requires: libgovirt-data = %{version}-%{release}
Provides: libgovirt-devel = %{version}-%{release}
Requires: libgovirt = %{version}-%{release}

%description dev
dev components for the libgovirt package.


%package lib
Summary: lib components for the libgovirt package.
Group: Libraries
Requires: libgovirt-data = %{version}-%{release}
Requires: libgovirt-license = %{version}-%{release}

%description lib
lib components for the libgovirt package.


%package license
Summary: license components for the libgovirt package.
Group: Default

%description license
license components for the libgovirt package.


%package locales
Summary: locales components for the libgovirt package.
Group: Default

%description locales
locales components for the libgovirt package.


%prep
%setup -q -n libgovirt-v0.3.7
cd %{_builddir}/libgovirt-v0.3.7

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1585773393
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir || :

%install
mkdir -p %{buildroot}/usr/share/package-licenses/libgovirt
cp %{_builddir}/libgovirt-v0.3.7/COPYING %{buildroot}/usr/share/package-licenses/libgovirt/9a1929f4700d2407c70b507b3b2aaf6226a9543c
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang govirt-1.0

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/GoVirt-1.0.typelib
/usr/share/gir-1.0/*.gir

%files dev
%defattr(-,root,root,-)
/usr/include/govirt-1.0/govirt/govirt.h
/usr/include/govirt-1.0/govirt/ovirt-api.h
/usr/include/govirt-1.0/govirt/ovirt-cdrom.h
/usr/include/govirt-1.0/govirt/ovirt-cluster.h
/usr/include/govirt-1.0/govirt/ovirt-collection.h
/usr/include/govirt-1.0/govirt/ovirt-data-center.h
/usr/include/govirt-1.0/govirt/ovirt-enum-types.h
/usr/include/govirt-1.0/govirt/ovirt-error.h
/usr/include/govirt-1.0/govirt/ovirt-host.h
/usr/include/govirt-1.0/govirt/ovirt-options.h
/usr/include/govirt-1.0/govirt/ovirt-proxy.h
/usr/include/govirt-1.0/govirt/ovirt-resource.h
/usr/include/govirt-1.0/govirt/ovirt-rest-call-error.h
/usr/include/govirt-1.0/govirt/ovirt-storage-domain.h
/usr/include/govirt-1.0/govirt/ovirt-types.h
/usr/include/govirt-1.0/govirt/ovirt-vm-display.h
/usr/include/govirt-1.0/govirt/ovirt-vm-pool.h
/usr/include/govirt-1.0/govirt/ovirt-vm.h
/usr/lib64/libgovirt.so
/usr/lib64/pkgconfig/govirt-1.0.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgovirt.so.2
/usr/lib64/libgovirt.so.2.2.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libgovirt/9a1929f4700d2407c70b507b3b2aaf6226a9543c

%files locales -f govirt-1.0.lang
%defattr(-,root,root,-)

