#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libgovirt
Version  : 0.3.4
Release  : 1
URL      : https://github.com/GNOME/libgovirt/archive/v0.3.4.tar.gz
Source0  : https://github.com/GNOME/libgovirt/archive/v0.3.4.tar.gz
Summary  : goVirt is a GLib binding for oVirt REST API
Group    : Development/Tools
License  : LGPL-2.1
Requires: libgovirt-data
Requires: libgovirt-lib
Requires: libgovirt-locales
BuildRequires : gettext
BuildRequires : gnome-common
BuildRequires : gobject-introspection-dev
BuildRequires : intltool
BuildRequires : intltool-dev
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(rest-0.7)

%description
GoVirt is a GObject wrapper for the oVirt REST API [1]. It will
only provide very basic functionality as the goal is to
autogenerate a full wrapper as it is already done for the python
bindings.

%package data
Summary: data components for the libgovirt package.
Group: Data

%description data
data components for the libgovirt package.


%package dev
Summary: dev components for the libgovirt package.
Group: Development
Requires: libgovirt-lib
Requires: libgovirt-data
Provides: libgovirt-devel

%description dev
dev components for the libgovirt package.


%package lib
Summary: lib components for the libgovirt package.
Group: Libraries
Requires: libgovirt-data

%description lib
lib components for the libgovirt package.


%package locales
Summary: locales components for the libgovirt package.
Group: Default

%description locales
locales components for the libgovirt package.


%prep
%setup -q -n libgovirt-0.3.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1519081530
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1519081530
rm -rf %{buildroot}
%make_install
%find_lang libgovirt

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/GoVirt-1.0.typelib
/usr/share/gir-1.0/*.gir

%files dev
%defattr(-,root,root,-)
/usr/include/govirt-1.0/govirt/govirt.h
/usr/include/govirt-1.0/govirt/ovirt-api.h
/usr/include/govirt-1.0/govirt/ovirt-cdrom.h
/usr/include/govirt-1.0/govirt/ovirt-collection.h
/usr/include/govirt-1.0/govirt/ovirt-enum-types.h
/usr/include/govirt-1.0/govirt/ovirt-error.h
/usr/include/govirt-1.0/govirt/ovirt-options.h
/usr/include/govirt-1.0/govirt/ovirt-proxy.h
/usr/include/govirt-1.0/govirt/ovirt-resource.h
/usr/include/govirt-1.0/govirt/ovirt-rest-call-error.h
/usr/include/govirt-1.0/govirt/ovirt-storage-domain.h
/usr/include/govirt-1.0/govirt/ovirt-types.h
/usr/include/govirt-1.0/govirt/ovirt-vm-display.h
/usr/include/govirt-1.0/govirt/ovirt-vm-pool.h
/usr/include/govirt-1.0/govirt/ovirt-vm.h
/usr/lib64/libgovirt.so
/usr/lib64/pkgconfig/govirt-1.0.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgovirt.so.2
/usr/lib64/libgovirt.so.2.1.0

%files locales -f libgovirt.lang
%defattr(-,root,root,-)

